language: python
matrix:
  include:
    - python: 3.6
      dist: xenial
      sudo: true
before_install:
  - pip install --upgrade pip
install:
  - pip install -e .
script:
  - python places_summarized/test.py